### ISSUE TITLE
Environment variable EGI_SITE not used

### ISSUE THREAD

**Issue by thebe14** [EGI-Federation/fedcloud-catchall-operations#207]
The environment variable `EGI_SITE` is set to a site name, but **fedcloud** does not use it, instead it insists to provide parameter `--site` or `--all-sites`.

## Environment

- Operating System: Ubuntu 22.04
- Other related components versions: fedcloud version 1.2.15

## Steps to reproduce

- Provision a new VM
- Install fedcloudclient
- Set environment variable `EGI_VO` and `EGI_SITE`
- Run command e.g. `fedcloud openstack server list`

Error message is shown:

```text
Error: Missing one of the required mutually exclusive options from 'Site' option group:
  '--site'
  '--all-sites' / '-a'
```

**Comment by thebe14** [comment]
Same thing happens on Windows (fedcloud version 1.2.14).

**Comment by andrea-manzi** [comment]
i think this is for https://github.com/tdviet/fedcloudclient

**Comment by thebe14** [comment]
You are right, moving it
